name: Python CI
on: pull_request

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.0"]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./scripts/integrations-cli
        run: pip install -r requirements.txt
      - uses: abatilo/pytest-action@v2
        name: Run pytest
        working-directory: ./scripts/integrations-cli
        with:
          job-summary: false
