name: Integrations CLI Test and Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'scripts/integrations-cli'
      - '.github/workflows/python-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/integrations-cli
    strategy:
      matrix:
        python-version: [3.8]
        opensearch-version: [ latest ]

    steps:
      - name: Checkout Integrations CLI
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel
      
      - name: Run Tests
        run: pytest
